# -*- coding: utf-8 -*-
"""juegoadivinansa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e00WIDQFxwi7JZ8O1uPGIxrDLc1zqVvY
"""

import random
#===========================================
# VERSION MAS BASICA DE
# JUEGO DE ADIVINANZAS
#===========================================

print("Bienvenido al juego de adivinanzas!" )
print("Adivina numero entre 0 y 100")

# 1. Genera numero secreto aleatorio
numero_secreto = random.randint(0, 100)

#2. Dar intentos al jugador
intentos_maximos = 10
intentos_usados = 0
#3. Bucle principal mientras tenga intentos
while intentos_usados < intentos_maximos:

   # Show reals intentos
   print(f"\n Intentos restantes: {intentos_maximos - intentos_usados}")
   # Pedir numero al jugador
   intento = int(input("Ingresa un numero: "))
   # Incrementar intentos usados
   intentos_usados += 1
   # Calcular diferecia distancia
   # abs() = valor absoluto (convierte negativos en positivos)
   diferencia = abs(intento - numero_secreto)


   #4. Verificar si adivino
   if intento == numero_secreto:
      print(f"¡Felicidades! Adivinaste el numero en {intentos_usados} intentos.")
      print(f"Lo adivinaste en {intentos_usados}")
      break
   #5. Dar pistas - Mayor o menor
   if intento < numero_secreto:
   #   print("El numero es mayor.")
      direccion = "mayor"
   elif intento > numero_secreto:
   #   print("El numero es menor.")
      direccion = "menor"

   # Dar pistas
   if diferencia <= 20:
      print(f"🔥 MUY CALIENTE El numero es {direccion}")
      print(f" (Estas a solo {diferencia} de distancia)")
   elif diferencia <= 40:
      print(f"♨️ CALIENTE El numero es {direccion}")
      print(f" (Estas a solo {diferencia} de distancia)")
   elif diferencia <= 60:
      print(f"❄️ FRIO El numero es {direccion}")
      print(f" (Estas a solo {diferencia} de distancia)")
   else:
      print(f"🧊 MUY FRIO El numero es {direccion}")
      print(f" (Estas a solo {diferencia} de distancia)")

# Si salio del bucle sin adivinar
else:
   print("Lo siento, has agotado los intentos.")
   print(f"\n Perdiste. El numero era {numero_secreto}")